FROM node:18-alpine AS BUILD_IMAGE

WORKDIR /usr/src/

COPY package.json package-lock.json ./

# install dependencies
RUN npm install

COPY . .

# build application
RUN npm run build

FROM nginx:latest
RUN rm -rf /etc/nginx/nginx.conf
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=BUILD_IMAGE /usr/src/dist /usr/share/nginx/html

EXPOSE 80